# Site settings
title: Long Hoang Dang
# general_email: your_general_email@gmail.com
academic_email: hldang@deakin.edu.au

#description: > # this means to ignore newlines until "baseurl:"
#  Give a brief description of yourself, and maybe your passion/interests. It is displayed in search results.

# baseurl: "/academic-portfolio" # the subpath of your site, e.g. /blog/

url: "https://longhoangdang.github.io" # the base hostname & protocol for your site

twitter_username: https://twitter.com/hldang96
github_username: https://github.com/longhoangdang
linkedin_username: linkedin.com/in/long-hoang-dang-45b58b132
# facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
theme: jekyll-theme-slate
